package model;

import java.math.BigDecimal;

/**
 * Represents a template for a student fee (e.g., "Tuition Fee").
 * This defines the standard amount and properties for a fee type, matching the 'fees' table schema.
 */
public class FeeTemplate {
    private int feeTemplateId; // Maps to fee_id
    private String name;        // Maps to fee_name
    private BigDecimal defaultAmount; // Maps to amount

    // --- Constructors ---

    /**
     * Constructor for creating a new FeeTemplate (ID generated by DB).
     */
    public FeeTemplate(String name, BigDecimal defaultAmount) {
        this.name = name;
        this.defaultAmount = defaultAmount;
    }

    /**
     * Full constructor for retrieving FeeTemplate from the database.
     */
    public FeeTemplate(int feeTemplateId, String name, BigDecimal defaultAmount) {
        this.feeTemplateId = feeTemplateId;
        this.name = name;
        this.defaultAmount = defaultAmount;
    }

    // --- Getters and Setters ---

    public int getFeeTemplateId() {
        return feeTemplateId;
    }

    public void setFeeTemplateId(int feeTemplateId) {
        this.feeTemplateId = feeTemplateId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getDefaultAmount() {
        return defaultAmount;
    }

    public void setDefaultAmount(BigDecimal defaultAmount) {
        this.defaultAmount = defaultAmount;
    }
}